- name: Copy elasticsearch rpm file to server
  become: no
  copy:
    src: elasticsearch-7.13.2-x86_64.rpm 
    dest: /tmp/elasticsearch-7.13.2-x86_64.rpm
    force: yes
    mode: 0644

- name: Copy GPG Key
  become: no
  copy:
    src: GPG-KEY-elasticsearch
    dest: /tmp/GPG-KEY-elasticsearch
    force: yes
    mode: 0644
    
- name: Import GPG Key
  rpm_key:
    state: present
    key: /tmp/GPG-KEY-elasticsearch
    
- name: Install elasticsearch
  yum:
    name: /tmp/elasticsearch-7.13.2-x86_64.rpm
    state: present

- name: Create elasticsearch configuration file
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    mode: 0644

- name: Create custom path data directory
  file:
    path: "{{ elasticsearch_path_data }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755
  when: elasticsearch_path_data is defined

- name: Create custom log directory
  file:
    path: "{{ elasticsearch_path_logs }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755
  when: elasticsearch_path_logs is defined

- name: Add elasticsearch port to firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - "{{ elasticsearch_http_port }}/tcp"
    - 9300/tcp

- name: Restart elasticsearch services
  service:
    name: elasticsearch
    state: restarted
    enabled: yes